// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF6RhnAIpvcgOaG4E6EpU-YwFvdMIqCzE',
    appId: '1:423726466777:web:36edc6bd12d79d371be0c8',
    messagingSenderId: '423726466777',
    projectId: 'site-portfolio-9eebe',
    authDomain: 'site-portfolio-9eebe.firebaseapp.com',
    storageBucket: 'site-portfolio-9eebe.appspot.com',
    measurementId: 'G-6FEZNW0D68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCTMlnJBGvr2Xq5u-SfwnCCIC1HGjbx5I',
    appId: '1:423726466777:android:74f1b9ef7dde69361be0c8',
    messagingSenderId: '423726466777',
    projectId: 'site-portfolio-9eebe',
    storageBucket: 'site-portfolio-9eebe.appspot.com',
  );
}
